name: create-pr-next-main
run-name: ${{ github.actor }} is making a PR from next into main.
on:
  push:
    branches:
      - next
jobs:
  create-pr:
    name: Create PR
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: next

      - name: Create PR
        run: gh pr create -B main -H next --title 'Merge Next into Main' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
